version: '3.8'

services:
  app:
    container_name: fastapi_app_dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/app/cache
    volumes:
      - .:/app
      - hf_cache:/app/cache
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  hf_cache:
